version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
  exclusions:
    rules:
      - linters:
          - errcheck
        text: "Error return value of `logger.Sync` is not checked"

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
